### ISSUE TITLE
ERROR! Failed to install app '530870' (Disk write failure)

### ISSUE THREAD

**Issue by brcaswell** [antimodes201/empyrion-server#1] opened 2020-03-03 00:44 UTC
When using the latest, existing image `antimodes201/empyrion-server:latest`:

run `docker run --rm -it antimodes201/empyrion-server:latest`

![Disk write failure](https://user-images.githubusercontent.com/967010/75731088-56e5f080-5cb4-11ea-9a93-05662ced0500.png)

Note that I am a windows host

**Comment by brcaswell** [comment] 2020-03-03 02:44
this issue doesn't seem to actually relate to the host; it is related to steamapps folder bug in linux.  

Were you actually able to create a container from this image?  

---

I have a fix coming, it is a simple one.. also going to refactor to use `RUN printf "\n2\n"|apt-get install -y steamcmd` instead of pulling the tar file.  which means some of the folders and syslinks will be created in that respect... `/usr/games` and `/home/steamuser/.steam/`

**Comment by antimodes201** [comment] 2020-07-28 16:10
issue caused by OS conflict (linux -> win -> wine).  Issue was resolved in a fork designed for windows based docker systems.

**Closed as completed by antimodes201** 2020-07-28 16:10 UTC
